const axios = require('axios');
const { metaCache } = require('./cache');
const TMDB_BASE   = 'https://api.themoviedb.org/3';
const TMDB_POSTER = 'https://image.tmdb.org/t/p/w342';
const TMDB_BG     = 'https://image.tmdb.org/t/p/w1280';
const TMDB_THUMB  = 'https://image.tmdb.org/t/p/w300';

function headers(token) {
  return { Authorization: `Bearer ${token || process.env.TMDB_BEARER_TOKEN}`, 'Content-Type': 'application/json' };
  }

  async function getMovieMeta(imdbId, token) {
    const cacheKey = `tmdb:movie:${imdbId}`;
      const cached = metaCache.get(cacheKey);
        if (cached) return cached;
          try {
              const findResp = await axios.get(`${TMDB_BASE}/find/${imdbId}`, {
                    headers: headers(token), params: { external_source: 'imdb_id' }
                        });
                            const movie = findResp.data.movie_results?.[0];
                                if (!movie) return null;
                                    const { data } = await axios.get(`${TMDB_BASE}/movie/${movie.id}`, {
                                          headers: headers(token), params: { append_to_response: 'credits,external_ids,videos' }
                                              });
                                                  const meta = {
                                                        id: imdbId, type: 'movie', name: data.title,
                                                              poster:      data.poster_path   ? `${TMDB_POSTER}${data.poster_path}`   : null,
                                                                    background:  data.backdrop_path ? `${TMDB_BG}${data.backdrop_path}`     : null,
                                                                          description: data.overview,
                                                                                releaseInfo: data.release_date?.slice(0, 4) || null,
                                                                                      imdbRating:  data.vote_average ? String(data.vote_average.toFixed(1)) : null,
                                                                                            runtime:     data.runtime ? `${data.runtime}m` : null,
                                                                                                  genres:      data.genres?.map(g => g.name) || [],
                                                                                                        cast:        data.credits?.cast?.slice(0, 10).map(c => c.name) || [],
                                                                                                              director:    data.credits?.crew?.filter(c => c.job === 'Director').map(c => c.name) || [],
                                                                                                                    trailers:    data.videos?.results?.filter(v => v.site === 'YouTube' && v.type === 'Trailer').map(v => ({ source: v.key, type: 'Trailer' })) || [],
                                                                                                                        };
                                                                                                                            metaCache.set(cacheKey, meta);
                                                                                                                                return meta;
                                                                                                                                  } catch (err) { console.error(`[tmdb] getMovieMeta failed for ${imdbId}:`, err.message); return null; }
                                                                                                                                  }
                                                                                                                                  
                                                                                                                                  async function getSeriesMeta(imdbId, token) {
                                                                                                                                    const cacheKey = `tmdb:series:${imdbId}`;
                                                                                                                                      const cached = metaCache.get(cacheKey);
                                                                                                                                        if (cached) return cached;
                                                                                                                                          try {
                                                                                                                                              const findResp = await axios.get(`${TMDB_BASE}/find/${imdbId}`, {
                                                                                                                                                    headers: headers(token), params: { external_source: 'imdb_id' }
                                                                                                                                                        });
                                                                                                                                                            const show = findResp.data.tv_results?.[0];
                                                                                                                                                                if (!show) return null;
                                                                                                                                                                    const { data } = await axios.get(`${TMDB_BASE}/tv/${show.id}`, {
                                                                                                                                                                          headers: headers(token), params: { append_to_response: 'credits,external_ids,videos' }
                                                                                                                                                                              });
                                                                                                                                                                                  const meta = {
                                                                                                                                                                                        id: imdbId, type: 'series', name: data.name,
                                                                                                                                                                                              poster:      data.poster_path   ? `${TMDB_POSTER}${data.poster_path}`   : null,
                                                                                                                                                                                                    background:  data.backdrop_path ? `${TMDB_BG}${data.backdrop_path}`     : null,
                                                                                                                                                                                                          description: data.overview,
                                                                                                                                                                                                                releaseInfo: data.first_air_date
                                                                                                                                                                                                                        ? data.status === 'Ended'
                                                                                                                                                                                                                                  ? `${data.first_air_date.slice(0,4)}-${data.last_air_date?.slice(0,4)||''}`
                                                                                                                                                                                                                                            : `${data.first_air_date.slice(0,4)}-`
                                                                                                                                                                                                                                                    : null,
                                                                                                                                                                                                                                                          imdbRating:  data.vote_average ? String(data.vote_average.toFixed(1)) : null,
                                                                                                                                                                                                                                                                genres:      data.genres?.map(g => g.name) || [],
                                                                                                                                                                                                                                                                      cast:        data.credits?.cast?.slice(0, 10).map(c => c.name) || [],
                                                                                                                                                                                                                                                                            director:    data.created_by?.map(c => c.name) || [],
                                                                                                                                                                                                                                                                                  trailers:    data.videos?.results?.filter(v => v.site === 'YouTube' && v.type === 'Trailer').map(v => ({ source: v.key, type: 'Trailer' })) || [],
                                                                                                                                                                                                                                                                                        _tmdbId:     show.id,
                                                                                                                                                                                                                                                                                              _numSeasons: data.number_of_seasons,
                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                      metaCache.set(cacheKey, meta);
                                                                                                                                                                                                                                                                                                          return meta;
                                                                                                                                                                                                                                                                                                            } catch (err) { console.error(`[tmdb] getSeriesMeta failed for ${imdbId}:`, err.message); return null; }
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            async function getSeasonEpisodes(tmdbId, seasonNum, token) {
                                                                                                                                                                                                                                                                                                              const cacheKey = `tmdb:season:${tmdbId}:${seasonNum}`;
                                                                                                                                                                                                                                                                                                                const cached = metaCache.get(cacheKey);
                                                                                                                                                                                                                                                                                                                  if (cached) return cached;
                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                        const { data } = await axios.get(`${TMDB_BASE}/tv/${tmdbId}/season/${seasonNum}`, { headers: headers(token) });
                                                                                                                                                                                                                                                                                                                            const episodes = data.episodes?.map(ep => ({
                                                                                                                                                                                                                                                                                                                                  id:       `${ep.show_id}:${seasonNum}:${ep.episode_number}`,
                                                                                                                                                                                                                                                                                                                                        title:    ep.name,
                                                                                                                                                                                                                                                                                                                                              season:   seasonNum,
                                                                                                                                                                                                                                                                                                                                                    episode:  ep.episode_number,
                                                                                                                                                                                                                                                                                                                                                          overview: ep.overview,
                                                                                                                                                                                                                                                                                                                                                                released: ep.air_date ? new Date(ep.air_date).toISOString() : null,
                                                                                                                                                                                                                                                                                                                                                                      thumbnail:ep.still_path ? `${TMDB_THUMB}${ep.still_path}` : null,
                                                                                                                                                                                                                                                                                                                                                                          })) || [];
                                                                                                                                                                                                                                                                                                                                                                              metaCache.set(cacheKey, episodes);
                                                                                                                                                                                                                                                                                                                                                                                  return episodes;
                                                                                                                                                                                                                                                                                                                                                                                    } catch { return []; }
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                    module.exports = { getMovieMeta, getSeriesMeta, getSeasonEpisodes };
